{
 "title": "4 golden signals",
 "description": "ОТУС Домашнее задание 15\n4 golden signals",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus 4 golden signals Errors/Minute",
   "type": "barchart",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nErrors\nЧастота ошибок или количество ошибок. Это могут быть некорректные коды ответа, исключения в приложении и тд. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", status=~\"4.+|5.+\"}[1m])) by (status) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus 4 golden signals Traffic",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nTraffic (Rate)\n Объем трафика или какой-то объем нагрузки, который вы обрабатываете прямо сейчас, обычно это RPS, RPM и тд.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus 4 golden signals Saturation",
   "type": "timeseries",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nSaturation\nЭта метрика помогает отвечать на вопрос, на сколько загружено наше приложение. Допустим оно обрабатывает 150 запросов в секунду, а можем ли мы обработать 200 или 250 или мы уже загружены под 100% и больше не получится? Отметим, что многие приложения и системы деградируют еще сильно до того, как saturation достиг 100%. \n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\"}[1m])) / max(rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Otus 4 golden signals Latency",
   "type": "barchart",
   "description": "Домашнее задание 15\nDashboard 4 golden signals\nLatency (Duration)\nЗадержка или время выполнения HTTP запроса, в зависимости от приложения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri!~\".*actuator.*\", status=~\"2.+\", instance=\"$instance\", job=\"$job\"}[1m])) by (le, uri))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}