apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appname }}
      {{- if hasKey .Values "tier" }}
      tier: {{ .Values.tier }}
      {{- end }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appname }}
        {{- if hasKey .Values "tier" }}
        tier: {{ .Values.tier }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.appname }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
             - containerPort: {{ .Values.port }}
               name: grpcclient
