appname: grpcserver
protocol: TCP
port: 8000
nodePort: 30102
namespace: cqrsesprojnamespace
tier: grpcserver
replicas: 1
image:
  repository: alekseyfilatov/docker-grps-grpcserver:latest
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  port: 8000
  nodePort: 30102