apiVersion: v1
kind: PersistentVolume
metadata:
    namespace: cqrsesprojnamespace
    name: mongodb-pv
spec:
  capacity:
    storage: 50M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storageclass
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: size
          operator: In
          values:
            - large