apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongodb-pvc
 namespace: cqrsesprojnamespace
spec:
 accessModes:
    - ReadWriteOnce
 resources:
    requests:
        storage: 50M # Adjust storage size as per your requirements