apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: cqrsesprojnamespace
  labels:
    app: postgres-container
data:
  POSTGRES_DB: microservices
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRESQL_SERVICE_NAME: postgres-service
  POSTGRESQL_PORT: "5432"