apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: cqrsesprojnamespace
  labels:
    app: postgres-service
spec:
  selector:
    app: postgres-container
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30003 #Внешний порт для работы с БД
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: cqrsesprojnamespace
  labels:
    app: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      namespace: cqrsesprojnamespace
      labels:
        app: postgres-container
    spec:
      containers:
        - name: postgres-container
          image: postgres:16.0 # указываем образ из Docker Hub
          envFrom:
            - configMapRef:
                name: postgres-configuration
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
           claimName: postgres-pv-claim