apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: cqrsesprojnamespace
type: Opaque
# при работе с PosrgreSQL по умолчанию, без доп.настроек, необходимо кодировать креды в Base64 
# user : postgres = cG9zdGdyZXM=
# password : postgres = cG9zdGdyZXM=
# db : microservices = bWljcm9zZXJ2aWNlcw==
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: bWljcm9zZXJ2aWNlcw==